# Generated by Django 5.1 on 2024-08-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='corebackend.company')),
            ],
            options={
                'unique_together': {('Company', 'service')},
            },
        ),
    ]
