# Generated by Django 5.1 on 2024-08-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0003_alter_selectedservice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255)),
                ('selected_services', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedService',
        ),
    ]
