# Generated by Django 5.1 on 2024-08-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0004_serviceselection_delete_selectedservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('case_per_day', models.PositiveIntegerField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('total_case', models.PositiveIntegerField()),
                ('report_type', models.CharField(choices=[('digital', 'Digital'), ('hard-copy', 'Hard Copy')], max_length=50)),
                ('report_type_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
