# Generated by Django 5.1 on 2024-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0005_testcasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('case_per_day', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('total_case', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestCaseData',
        ),
    ]
