# Generated by Django 5.1 on 2024-08-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0007_pricerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pricerange',
            options={'ordering': ['service', 'max_cases']},
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='max_cases',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='corebackend.service'),
        ),
    ]
