# Generated by Django 5.1 on 2024-08-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0008_service_alter_pricerange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerange',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pricerange',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='max_cases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
