# Generated by Django 5.1 on 2024-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0009_alter_pricerange_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('travel', models.IntegerField(default=0)),
                ('stay', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
            ],
        ),
    ]
