# Generated by Django 5.1 on 2024-08-31 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0010_costdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('misc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corebackend.testtype')),
            ],
        ),
    ]
