# Generated by Django 5.1 on 2024-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0012_servicecost_consumables_servicecost_reporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='estimations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
