# Generated by Django 5.1 on 2024-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0014_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdetails',
            name='consumables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='equipment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='incentive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='misc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='reporting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
