# Generated by Django 5.1 on 2024-09-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0015_costdetails_consumables_costdetails_equipment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
