# Generated by Django 5.1 on 2024-09-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0016_delete_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdetails',
            name='incentive',
            field=models.IntegerField(),
        ),
    ]
