# Generated by Django 5.1 on 2024-09-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0017_alter_costdetails_incentive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costdetails',
            name='incentive',
        ),
    ]
