# Generated by Django 5.1 on 2024-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0018_remove_costdetails_incentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
