# Generated by Django 5.1 on 2024-09-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0019_discountcoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
