# Generated by Django 5.1 on 2024-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0020_rename_created_at_pdfdocument_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='created_at',
            field=models.DateTimeField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
    ]
