# Generated by Django 5.1 on 2024-09-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0021_remove_pdfdocument_uploaded_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
