# Generated by Django 5.1 on 2024-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0022_delete_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='estimations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
