# Generated by Django 5.1 on 2024-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0023_estimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255)),
                ('billing_number', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_state', models.CharField(blank=True, max_length=255, null=True)),
                ('company_district', models.CharField(blank=True, max_length=255, null=True)),
                ('company_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('company_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('camp_details', models.JSONField()),
                ('service_details', models.JSONField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
