# Generated by Django 5.1 on 2024-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0024_costsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hard_copy_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
