# Generated by Django 5.1 on 2024-09-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebackend', '0027_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
